In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
data = pd.read_excel(r'C:\Users\avdhu\OneDrive\Desktop\dataGYM.xlsx')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1176 entries, 0 to 1175
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Age         1176 non-null   int64  
 1   Height      1176 non-null   float64
 2   weight      1176 non-null   int64  
 3   BMI         1176 non-null   int64  
 4   Class       1176 non-null   object 
 5   Prediction  1176 non-null   object 
dtypes: float64(1), int64(3), object(2)
memory usage: 55.2+ KB


In [3]:
df = data.copy()

In [4]:
df.head(3)

Age  Height  weight  BMI            Class  \
0   48     4.1      86   40  Extremely obese   
1   53     4.1      91   42  Extremely obese   
2   42     4.1      95   44  Extremely obese   

                                          Prediction  
0  Extremely obese--normal exercise+yoga+heavy di...  
1  Extremely obese--normal exercise+yoga+heavy di...  
2  Extremely obese--normal exercise+yoga+heavy di...

In [5]:
df['Class'].unique()

array(['Extremely obese', 'Healthy\xa0', 'Obese', 'Overweight',
       'Under weight', 'EXtremely obese'], dtype=object)

In [6]:
#correcting typo error
df['Class'] = df['Class'].replace({'EXtremely obese':'Extremely obese','Healthy\xa0':'Healthy'})
df['Class'].unique()

array(['Extremely obese', 'Healthy', 'Obese', 'Overweight',
       'Under weight'], dtype=object)

In [7]:
df['Class'].value_counts()

Obese              281
Under weight       248
Healthy            232
Extremely obese    216
Overweight         199
Name: Class, dtype: int64

In [8]:
df['Prediction'].value_counts()

Obese--slow lean+protine+full dite ->Overweight                          281
Under weight--protines+carbs+normal weights ->Healthy                    248
Healthy--fitness+protine+simple dite                                     232
Extremely obese--normal exercise+yoga+heavy dite control+TIPS ->Obese    216
Overweight--lean+cardio+protine+normal dite ->Healthy                    199
Name: Prediction, dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder
df['Class'] = LabelEncoder().fit_transform(df['Class'])
df.head(3)

Age  Height  weight  BMI  Class  \
0   48     4.1      86   40      0   
1   53     4.1      91   42      0   
2   42     4.1      95   44      0   

                                          Prediction  
0  Extremely obese--normal exercise+yoga+heavy di...  
1  Extremely obese--normal exercise+yoga+heavy di...  
2  Extremely obese--normal exercise+yoga+heavy di...

In [10]:
df['Prediction'] = LabelEncoder().fit_transform(df['Prediction'])
df.tail()

Age  Height  weight  BMI  Class  Prediction
1171   50     6.9      59   14      4           4
1172   49     6.9      64   15      4           4
1173   52     6.9      68   16      4           4
1174   36     6.9      73   17      4           4
1175   26     6.9      77   18      4           4

In [24]:
#splitting into training and testing 
X = df.iloc[:,:3].to_numpy()
X

array([[48. ,  4.1, 86. ],
       [53. ,  4.1, 91. ],
       [42. ,  4.1, 95. ],
       ...,
       [52. ,  6.9, 68. ],
       [36. ,  6.9, 73. ],
       [26. ,  6.9, 77. ]])

In [12]:
y = df.iloc[:,5:]

In [13]:
y

Prediction
0              0
1              0
2              0
3              0
4              0
...          ...
1171           4
1172           4
1173           4
1174           4
1175           4

[1176 rows x 1 columns]

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 0)

In [26]:
print(X_train.shape)
print('----------')
print(X_test.shape)
print('----------')
print(y_train.shape)
print('----------')
print(y_test.shape)

(940, 3)
----------
(236, 3)
----------
(940, 1)
----------
(236, 1)


In [27]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier()
gbc.fit(X_train,y_train.values.ravel()) #ravel() = Return a flattened array.
gbc.score(X_test,y_test)

0.8305084745762712

In [28]:
from sklearn.metrics import classification_report, confusion_matrix


In [29]:
gb_clf2 = GradientBoostingClassifier()
gb_clf2.fit(X_train,y_train.values.ravel())
predictions = gb_clf2.predict(X_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions))

print("Classification Report")
print(classification_report(y_test, predictions))


Confusion Matrix:
[[33  0  3  0  0]
 [ 0 43  0  3  3]
 [ 5  0 44  4  0]
 [ 0 11  6 29  0]
 [ 0  5  0  0 47]]
Classification Report
              precision    recall  f1-score   support

           0       0.87      0.92      0.89        36
           1       0.73      0.88      0.80        49
           2       0.83      0.83      0.83        53
           3       0.81      0.63      0.71        46
           4       0.94      0.90      0.92        52

    accuracy                           0.83       236
   macro avg       0.83      0.83      0.83       236
weighted avg       0.83      0.83      0.83       236



In [30]:
import pickle

pickle.dump(gbc,open('MODEL_GYM_AP.pkl','wb'))


In [31]:
model = pickle.load(open('MODEL_GYM_AP.pkl','rb'))

In [32]:
model

GradientBoostingClassifier()

In [33]:
print(model.predict([[40,5.6,70]]))


[1]
